=== lucianoScotellaro/SWA-WebMarketRESTfulAPI/schemas/request.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://swa.net/schemas/request",
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "minimum": 1
      },
      "orderer": {
        "$ref": "/schemas/user"
      },
      "technician": {
        "$ref": "/schemas/user"
      },
      "category": {
        "type": "string"
      },
      "characteristics": {
        "type": "object"
      },
      "notes": {
        "type": "string"
      },
      "proposal": {
        "$ref": "/schemas/proposal"
      },
      "ongoing": {
        "type": "boolean"
      },
      "outcome": {
        "type": "string",
        "enum": [
          "accepted",
          "rejected as non compliant",
          "rejected as defective"
        ]
      }
    },
    "required": [
      "id",
      "orderer",
      "technician",
      "category",
      "characteristics",
      "notes",
      "proposal",
      "ongoing",
      "outcome"
    ],
    "additionalProperties": false
  }

=== lucianoScotellaro/SWA-WebMarketRESTfulAPI/examples/request.json
{
  "id": 1,
  "orderer": {
    "id": 12,
    "username": "pippo",
    "email": "pippo@gmail.com"
  },
  "technician": {
    "id": 13,
    "username": "pluto",
    "email": "pluto@gmail.com"
  },
  "category": "informatic",
  "characteristics": {
    "GPU": "RTX4090Ti",
    "CPU": "Ryzen5600X",
    "RAM": "32GB"
  },
  "notes": "Vorrei un bel computer",
  "proposal": {
    "product": {
      "name": "HP qualcosa",
      "producer": "HP",
      "id": 1,
      "price": 799.99,
      "url": "www.youtube.com"
    },
    "notes": "Questo e` proprio un bel computer",
    "answer": {
      "accepted": true,
      "reason": ""
    }
  },
  "ongoing": false,
  "outcome": "accepted"
}
